import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const AWARDS_DIR = path.join(ROOT, "docs/public/awards");
const OUT_FILE = path.join(
  ROOT,
  "docs/.vitepress/theme/data/awardPhotos.generated.js"
);

const IMAGE_EXTS = new Set([".webp", ".jpg", ".jpeg", ".png"]);

/**
 * Scan docs/public/awards/<slug>/ and write a JS module map.
 * Empty / missing dirs are omitted — consumers treat missing keys as "no photos".
 * @returns {Record<string, string[]>}
 */
export function scanAwards() {
  /** @type {Record<string, string[]>} */
  const result = {};

  if (fs.existsSync(AWARDS_DIR)) {
    for (const entry of fs.readdirSync(AWARDS_DIR, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      if (entry.name.startsWith(".")) continue;

      const slug = entry.name;
      const dir = path.join(AWARDS_DIR, slug);
      const files = fs
        .readdirSync(dir)
        .filter((name) => IMAGE_EXTS.has(path.extname(name).toLowerCase()))
        .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))
        .map((name) => `/awards/${slug}/${name}`);

      if (files.length > 0) {
        result[slug] = files;
      }
    }
  }

  writeManifest(result);
  return result;
}

/** @param {Record<string, string[]>} result */
function writeManifest(result) {
  const json = JSON.stringify(result, null, 2);
  const contents = `/** Auto-generated by scripts/awards-scan.mjs — do not edit. */\nexport default ${json};\n`;

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });

  const prev = fs.existsSync(OUT_FILE) ? fs.readFileSync(OUT_FILE, "utf8") : "";
  if (prev !== contents) {
    fs.writeFileSync(OUT_FILE, contents, "utf8");
  }
}

/**
 * Vite plugin: scan on buildStart, watch awards dir in dev.
 * @returns {import('vite').Plugin}
 */
export function awardsPhotosPlugin() {
  return {
    name: "awards-photos-scan",
    buildStart() {
      scanAwards();
    },
    configureServer(server) {
      scanAwards();

      const watchRoot = fs.existsSync(AWARDS_DIR)
        ? AWARDS_DIR
        : path.join(ROOT, "docs/public");

      server.watcher.add(watchRoot);

      const rescan = (file) => {
        const normalized = file.replace(/\\/g, "/");
        if (!normalized.includes("/awards")) return;
        scanAwards();
        const mod = server.moduleGraph.getModuleById(OUT_FILE);
        if (mod) {
          server.moduleGraph.invalidateModule(mod);
        }
        server.ws.send({ type: "full-reload" });
      };

      server.watcher.on("add", rescan);
      server.watcher.on("unlink", rescan);
      server.watcher.on("change", rescan);
      server.watcher.on("addDir", rescan);
      server.watcher.on("unlinkDir", rescan);
    },
  };
}

// CLI: node scripts/awards-scan.mjs
const isDirectRun = process.argv[1]
  ? path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
  : false;

if (isDirectRun) {
  const result = scanAwards();
  const slugs = Object.keys(result);
  console.log(
    `[awards-scan] ${slugs.length} slug(s) with photos → ${path.relative(ROOT, OUT_FILE)}`
  );
  for (const slug of slugs) {
    console.log(`  - ${slug}: ${result[slug].length} image(s)`);
  }
}
