name: Deploy

on: workflow_dispatch
# on:
#   push:
#     branches:
#       - main

jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - name: 拉取程式碼
          uses: actions/checkout@v4
          with: 
            fetch-depth: 0
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i pnpm -g
      - run: pnpm install
      - run: pnpm generate-sidebar
      
      - name: Create .env file
        run: echo "VITE_GOOGLE_ANALYTICS_ID=${{ secrets.VITE_GOOGLE_ANALYTICS_ID }}" > .env

      - name: Build
        run: pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: docs/.vitepress/dist